version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_books
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: books_db
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
